services:
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm start:debug auth
    ports:
      - "3001:3001"
      - "9229:9229"
    env_file:
      - ./apps/auth/.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/apps/auth/node_modules
  phimmoi:
    build:
      context: .
      dockerfile: ./apps/phimmoi/Dockerfile
      target: development
    command: pnpm start:debug phimmoi
    env_file:
      - ./apps/phimmoi/.env
    ports:
      - "3003:3003"
      - "9235:9229"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/apps/phimmoi/node_modules

  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: pnpm start:debug payments
    env_file:
      - ./apps/payments/.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/apps/payments/node_modules
  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: pnpm start:debug notifications
    env_file:
      - ./apps/notifications/.env
    ports:
      - "9232:9229"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/apps/notifications/node_modules
  area:
    build:
      context: .
      dockerfile: ./apps/area/Dockerfile
      target: development
    command: pnpm start:debug area
    ports:
      - "3005:3005"
      - "9231:9229"
    env_file:
      - ./apps/area/.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/apps/area/node_modules
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
      