services:
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm start:dev auth
    ports:
      - "9001:9001"
    env_file:
      - ./apps/auth/.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/apps/auth/node_modules
  phimmoi:
    build:
      context: .
      dockerfile: ./apps/phimmoi/Dockerfile
      target: development
    command: pnpm start:dev phimmoi
    env_file:
      - ./apps/phimmoi/.env
    ports:
      - "9000:9000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/apps/phimmoi/node_modules

  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: pnpm start:dev payments
    env_file:
      - ./apps/payments/.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/apps/payments/node_modules
  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: pnpm start:dev notifications
    env_file:
      - ./apps/notifications/.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/apps/notifications/node_modules
  mongo:
    logging:
      driver: "none"
    command: mongod --quiet
    image: mongo:latest
