apiVersion: v1
kind: Service
metadata:
  labels:
    app: phimmoi
  name: phimmoi
spec:
  ports:
    - name: "http"
      port: 3003
      protocol: TCP
      targetPort: 3003  
  selector:
    app: phimmoi
  type: NodePort
