apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - image: asia-east2-docker.pkg.dev/triple-shift-463315-e6/auth/production
          name: auth
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: connectionString
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: secretKey
            - name: JWT_EXPIRES_IN
              value: "3600"
            - name: HTTP_PORT
              value: "3001"
            - name: TCP_PORT
              value: "3002"
          ports:
            - containerPort: 3001
            - containerPort: 3002
