apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
      - image: asia-east2-docker.pkg.dev/triple-shift-463315-e6/notifications/production
        name: notifications
        env:
          - name: MONGO_URI
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: connectionString
          - name: GMAIL_CLIENT_ID
            value: "917475912707-usohdpfiaptbhqru2o7gioc1hg20ms2u.apps.googleusercontent.com"
          - name: GMAIL_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: google
                key: clientSecret
          - name: GMAIL_REFRESH_TOKEN
            valueFrom:
              secretKeyRef:
                name: gmail
                key: refreshToken
          - name: STMP_USER
            value: "q96272212@gmail.com"
          - name: PORT
            value: "3000"
        ports:
          - containerPort: 3000